import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { executeFrameworkProject, fitIsotonicCalibration, freezeContextCorpus, normalizeProjectInput, parseFrameworkManifest, predictCompatibility, prepareFrameworkProject, renderFrameworkPreviewHtml } from "../dist/index.js";
import { createFixtureExecutor, createOrchestrationFixture } from "../fixtures/orchestration-fixture.mjs";

const manifestText=readFileSync(new URL("../../site-manifest.yaml",import.meta.url),"utf8");const manifest=parseFrameworkManifest(manifestText);const fixture=createOrchestrationFixture(manifest);

test("ProjectInput and ledgers are canonical under reordering",()=>{const first=normalizeProjectInput(fixture.project);const second=normalizeProjectInput({...fixture.project,sources:[...fixture.project.sources].reverse(),assets:[...fixture.project.assets].reverse()});assert.equal(first.projectHash,second.projectHash);assert.equal(first.validation.passes,true);assert.equal(first.sourceLedger.length,1);assert.equal(first.assetLedger.length,1);});
test("ContextCorpus freezes independent graded train validation test splits",()=>{const first=freezeContextCorpus(fixture.contextCorpus.id,fixture.contextCorpus.version,fixture.contextCorpus.cases,fixture.contextCorpus.splitPolicy,fixture.contextCorpus.generationAgentId);const second=freezeContextCorpus(fixture.contextCorpus.id,fixture.contextCorpus.version,[...fixture.contextCorpus.cases].reverse(),fixture.contextCorpus.splitPolicy,fixture.contextCorpus.generationAgentId);assert.equal(first.corpusHash,second.corpusHash);assert.deepEqual(first.splitHashes,second.splitHashes);assert.equal(new Set(first.cases.map((x)=>x.split)).size,3);assert.ok(first.cases.every((x)=>x.judgments.length>=2));});
test("isotonic compatibility is monotonic and ineligible fit is zero",()=>{const calibration=fitIsotonicCalibration("fixture",fixture.calibrationObservations);assert.equal(calibration.validationReport.passes,true);assert.equal(calibration.model.probabilities.every((value,index,values)=>index===0||value>=values[index-1]),true);assert.equal(predictCompatibility(calibration.model,0,false),0);assert.ok(predictCompatibility(calibration.model,0.95,true)>predictCompatibility(calibration.model,0.05,true));});
test("pipeline compiles explicit primaries selected corpus typed graph and jobs",()=>{const prepared=prepareFrameworkProject(fixture);assert.equal(prepared.project.validation.passes,true);assert.equal(prepared.contextCorpus.validation.passes,true);assert.equal(prepared.calibration.validationReport.passes,true);assert.equal(prepared.selectedCorpus.validation.passes,true);assert.equal(prepared.selectedCorpus.selected.length,2);assert.equal(prepared.selectedCorpus.rejected.length,1);assert.equal(prepared.generationJobs.length,2);const painting=prepared.generationJobs.find((x)=>x.pageId==="candidate:painting-estimate");assert.ok(painting);assert.equal(painting.primaryPrototypeId,"owner-estimate");assert.equal(painting.targetPrototypes[0].id,"owner-estimate");assert.ok(painting.generationPlan.includes("ui"));assert.ok(painting.requiredGraphEdges.length>0);});
test("agent runner performs bounded repair and preview exposes rejection reasons",async()=>{const prepared=prepareFrameworkProject(fixture);const executed=await executeFrameworkProject(prepared,createFixtureExecutor(),{maximumRepairAttempts:1});assert.equal(executed.generationRuns.every((x)=>x.status==="completed"),true);assert.ok(executed.generationRuns.some((x)=>x.events.some((event)=>event.state==="repair-started")));assert.equal(executed.preview.pages.length,prepared.generationJobs.length);assert.equal(executed.preview.rejectedPages.length,prepared.selectedCorpus.rejected.length);assert.ok(executed.preview.rejectedPages.every((x)=>x.reasons.length>0));assert.equal(executed.preview.validation.passes,true);const html=renderFrameworkPreviewHtml(executed.preview);assert.match(html,/Page generation jobs/);assert.match(html,/Rejected coordinates/);assert.match(html,/Validation reports/);assert.match(html,/candidate:painting-estimate/);});
