import type { ContextCase } from "./core.js";
import type { ContextCorpus, FrozenContextCase } from "./context-corpus.js";
import { greedyCompositeSelection, type CompositeCandidate } from "./optimizer.js";
import type { NormalizedProject } from "./project-input.js";
import { compileTypedGraph, type TypedPageGraph } from "./typed-graph.js";
import { buildValidationReport, finding, type ValidationReport } from "./validation-contracts.js";
import { ORCHESTRATION_VALIDATION, coordinateSimilarity, type PageCoordinate } from "./page-coordinate.js";
import { sha256 } from "./core.js";

export interface RejectedCoordinate { id:string; reasons:readonly string[]; }
export interface SelectedCorpusPlan { projectId:string; corpusId:string; selected:readonly PageCoordinate[]; rejected:readonly RejectedCoordinate[]; typedGraph:TypedPageGraph; objective:number; coverageObjective:number; informationObjective:number; rareTailObjective:number; diversityObjective:number; validationCoverage:number; testCoverage:number; budget:number; spent:number; planHash:string; validation:ValidationReport; }
export interface CorpusSelectionOptions { budget:number; informationWeight:number; rareTailWeight:number; diversityWeight:number; minimumValidationCoverage:number; minimumTestCoverage:number; }

export function selectCorpusPlan(project:NormalizedProject,corpus:ContextCorpus,coordinates:readonly PageCoordinate[],options:CorpusSelectionOptions):SelectedCorpusPlan{
  if(!Number.isFinite(options.budget)||options.budget<=0)throw new Error("selection budget must be positive");
  const train=corpus.cases.filter((x)=>x.split==="train");const candidateIds=coordinates.map((x)=>x.id);const similarities=train.map((context)=>coordinates.map((coordinate)=>coordinate.contextCompatibility.find((x)=>x.contextId===context.id)?.calibratedProbability??0));
  const contexts:ContextCase[]=train.map((x)=>({id:x.id,weight:x.weight,...(x.hiddenSliceIds?.[0]?{group:x.hiddenSliceIds[0]}:{})}));const candidates:CompositeCandidate[]=coordinates.map((x)=>({id:x.id,cost:x.lifecycleCost,informationObjectIds:x.informationObjectIds,rareGroups:x.rareGroupIds}));const kernel=coordinates.map((a)=>coordinates.map((b)=>coordinateSimilarity(a,b)));
  const result=greedyCompositeSelection({facility:{contexts,candidateIds,similarities,costs:coordinates.map((x)=>x.lifecycleCost),budget:options.budget},candidates,informationWeight:options.informationWeight,rareTailWeight:options.rareTailWeight,diversityWeight:options.diversityWeight,...(options.diversityWeight===0?{}:{similarityKernel:kernel})});
  const ids=new Set(result.selectedIds);const selected=coordinates.filter((x)=>ids.has(x.id)).sort((a,b)=>a.id.localeCompare(b.id));const rejected=coordinates.filter((x)=>!ids.has(x.id)).map((x)=>({id:x.id,reasons:rejectionReasons(x,selected)})).sort((a,b)=>a.id.localeCompare(b.id));const validationCoverage=meanCoverage(corpus.cases.filter((x)=>x.split==="validation"),selected);const testCoverage=meanCoverage(corpus.cases.filter((x)=>x.split==="test"),selected);const spent=selected.reduce((sum,x)=>sum+x.lifecycleCost,0);
  const graph=compileTypedGraph(selected.map((x)=>x.id),selected.flatMap((x)=>x.graphEdges.filter((edge)=>ids.has(edge.fromPageId)&&ids.has(edge.toPageId))));const pass=selected.length>0&&spent<=options.budget&&validationCoverage>=options.minimumValidationCoverage&&testCoverage>=options.minimumTestCoverage;
  const findings=[finding("coordinate.primary",selected.every((x)=>x.prototypes.some((p)=>p.id===x.primaryPrototypeId))?"pass":"fail","selected coordinates preserve primary prototypes"),finding("coordinate.eligibility",selected.every((x)=>x.contextCompatibility.some((f)=>f.eligible))?"pass":"fail","selected coordinates have eligible contexts"),finding("coordinate.specificity",selected.every((x)=>x.informationObjectIds.length>0)?"pass":"fail","selected coordinates retain information objects"),finding("selection.coverage",pass?"pass":"fail",`selected=${selected.length}, spent=${spent}/${options.budget}, validation=${validationCoverage.toFixed(4)}, test=${testCoverage.toFixed(4)}`,{measured:Math.min(validationCoverage,testCoverage),threshold:Math.min(options.minimumValidationCoverage,options.minimumTestCoverage)}),finding("selection.balance","pass",`coverage=${result.coverageObjective.toFixed(4)}, information=${result.informationObjective.toFixed(4)}, rare=${result.rareTailObjective.toFixed(4)}, diversity=${result.diversityObjective.toFixed(4)}`),finding("job.contract","pending","jobs not compiled"),finding("runner.checkpoints","pending","runner not executed"),finding("preview.operator","pending","preview not built")];
  const canonical={projectId:project.input.id,corpusId:corpus.id,selectedIds:selected.map((x)=>x.id),rejected,graphHash:graph.graphHash,objective:result.objective,coverageObjective:result.coverageObjective,informationObjective:result.informationObjective,rareTailObjective:result.rareTailObjective,diversityObjective:result.diversityObjective,validationCoverage,testCoverage,budget:options.budget,spent};
  return{projectId:project.input.id,corpusId:corpus.id,selected,rejected,typedGraph:graph,objective:result.objective,coverageObjective:result.coverageObjective,informationObjective:result.informationObjective,rareTailObjective:result.rareTailObjective,diversityObjective:result.diversityObjective,validationCoverage,testCoverage,budget:options.budget,spent,planHash:sha256(JSON.stringify(canonical)),validation:buildValidationReport(`selected-corpus:${project.input.id}`,ORCHESTRATION_VALIDATION,findings)};
}
function meanCoverage(contexts:readonly FrozenContextCase[],coordinates:readonly PageCoordinate[]):number{const total=contexts.reduce((s,x)=>s+x.weight,0);return total===0?0:contexts.reduce((sum,c)=>sum+c.weight*coordinates.reduce((best,p)=>Math.max(best,p.contextCompatibility.find((x)=>x.contextId===c.id)?.calibratedProbability??0),0),0)/total;}
function rejectionReasons(item:PageCoordinate,selected:readonly PageCoordinate[]):string[]{const out:string[]=[];if(item.contextCompatibility.every((x)=>x.calibratedProbability===0))out.push("zero eligible calibrated coverage");const closest=selected.reduce((best,x)=>Math.max(best,coordinateSimilarity(item,x)),0);if(closest>=0.9)out.push(`redundant with selected corpus (${closest.toFixed(3)})`);if(item.lifecycleCost>1)out.push(`higher lifecycle cost ${item.lifecycleCost}`);if(out.length===0)out.push("lower marginal objective under current budget");return out;}
