import { sha256 } from "./core.js";
import type { ContextCorpus } from "./context-corpus.js";
import type { SelectedCorpusPlan, RejectedCoordinate } from "./corpus-plan.js";
import type { NormalizedProject } from "./project-input.js";
import type { GenerationRunResult, PageGenerationJob } from "./page-generation.js";
import { ORCHESTRATION_VALIDATION } from "./page-coordinate.js";
import { buildValidationReport, finding, type ValidationReport } from "./validation-contracts.js";

export interface FrameworkPreviewModel { project:{id:string;hash:string;businessPurpose:string;brandName:string}; corpus:{id:string;hash:string;counts:Record<string,number>}; plan:{hash:string;selectedCount:number;rejectedCount:number;objective:number;validationCoverage:number;testCoverage:number}; pages:readonly {id:string;route:string;question:string;primaryPrototypeId:string;prototypeCount:number;generationStatus:"pending"|"completed"|"rejected";hardFailures:readonly string[]}[]; rejectedPages:readonly RejectedCoordinate[]; validations:readonly ValidationReport[]; validation:ValidationReport; previewHash:string; }

export function buildFrameworkPreview(project:NormalizedProject,corpus:ContextCorpus,plan:SelectedCorpusPlan,jobs:readonly PageGenerationJob[],runs:readonly GenerationRunResult[],extra:readonly ValidationReport[]=[]):FrameworkPreviewModel{
  const runByJob=new Map(runs.map((x)=>[x.jobId,x]));const jobByPage=new Map(jobs.map((x)=>[x.pageId,x]));const pages=plan.selected.map((coordinate)=>{const job=jobByPage.get(coordinate.id);const run=job?runByJob.get(job.jobId):undefined;return{id:coordinate.id,route:coordinate.route,question:coordinate.canonicalQuestion,primaryPrototypeId:coordinate.primaryPrototypeId,prototypeCount:coordinate.prototypes.length,generationStatus:run?.status??"pending",hardFailures:run?.validation.hardFailures??[]};}).sort((a,b)=>a.id.localeCompare(b.id));const rejectedPages=plan.rejected.map((x)=>({id:x.id,reasons:[...x.reasons]}));const base=[project.validation,corpus.validation,plan.validation,...jobs.map((x)=>x.validation),...runs.map((x)=>x.validation),...extra];const counts=corpus.cases.reduce<Record<string,number>>((out,x)=>{out[x.split]=(out[x.split]??0)+1;return out;},{});
  const validation=buildValidationReport(`preview:${project.input.id}`,ORCHESTRATION_VALIDATION,[finding("coordinate.primary",pages.every((x)=>Boolean(x.primaryPrototypeId))?"pass":"fail","primary identity visible"),finding("coordinate.eligibility","pass","selected corpus consumed"),finding("coordinate.specificity",pages.every((x)=>Boolean(x.question.trim()))?"pass":"fail","questions visible"),finding("selection.coverage",plan.validation.passes?"pass":"fail","coverage status visible"),finding("selection.balance","pass","selected/rejected counts visible"),finding("job.contract",jobs.length===pages.length?"pass":"fail",`${jobs.length}/${pages.length} pages have jobs`),finding("runner.checkpoints",runs.length===0||runs.length===jobs.length?"pass":"fail",`${runs.length}/${jobs.length} runs recorded`),finding("preview.operator",rejectedPages.every((x)=>x.reasons.length>0)?"pass":"fail",`${rejectedPages.length} rejected coordinates have reasons`)]);const validations=[...base,validation];const canonical={project:{id:project.input.id,hash:project.projectHash,businessPurpose:project.input.business.purpose,brandName:project.input.brand.name},corpus:{id:corpus.id,hash:corpus.corpusHash,counts},plan:{hash:plan.planHash,selectedCount:plan.selected.length,rejectedCount:plan.rejected.length,objective:plan.objective,validationCoverage:plan.validationCoverage,testCoverage:plan.testCoverage},pages,rejectedPages,validations:validations.map((x)=>({scope:x.scope,hash:x.reportHash,passes:x.passes,hardFailures:x.hardFailures})),previewValidationHash:validation.reportHash};return{project:canonical.project,corpus:canonical.corpus,plan:canonical.plan,pages,rejectedPages,validations,validation,previewHash:sha256(JSON.stringify(canonical))};
}
export function renderFrameworkPreviewHtml(preview:FrameworkPreviewModel):string{const rows=preview.pages.map((x)=>`<tr><td>${e(x.id)}</td><td><code>${e(x.route)}</code></td><td>${e(x.question)}</td><td>${e(x.primaryPrototypeId)}</td><td>${x.prototypeCount}</td><td>${e(x.generationStatus)}</td><td>${e(x.hardFailures.join(", ")||"none")}</td></tr>`).join("");const rejected=preview.rejectedPages.map((x)=>`<tr><td>${e(x.id)}</td><td>${e(x.reasons.join("; "))}</td></tr>`).join("");const reports=preview.validations.map((x)=>`<tr><td>${e(x.scope)}</td><td>${x.passes?"pass":"fail"}</td><td>${e(x.hardFailures.join(", ")||"none")}</td><td><code>${e(x.reportHash.slice(0,16))}</code></td></tr>`).join("");return`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Website Framework Project Preview</title><style>body{font-family:system-ui,sans-serif;margin:0;background:#f7f9fc;color:#111}main{max-width:1200px;margin:auto;padding:32px}section{background:#fff;border:1px solid #dbe3ef;border-radius:16px;padding:24px;margin:16px 0;overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #e7edf5;vertical-align:top}.metric{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}.metric div{border:1px solid #e7edf5;border-radius:12px;padding:12px}</style></head><body><main><h1>${e(preview.project.brandName)} website framework preview</h1><p>${e(preview.project.businessPurpose)}</p><section class="metric"><div><strong>Selected</strong><br>${preview.plan.selectedCount}</div><div><strong>Rejected</strong><br>${preview.plan.rejectedCount}</div><div><strong>Validation coverage</strong><br>${preview.plan.validationCoverage.toFixed(3)}</div><div><strong>Test coverage</strong><br>${preview.plan.testCoverage.toFixed(3)}</div></section><section><h2>Page generation jobs</h2><table><tbody>${rows}</tbody></table></section><section><h2>Rejected coordinates</h2><table><tbody>${rejected}</tbody></table></section><section><h2>Validation reports</h2><table><tbody>${reports}</tbody></table></section></main></body></html>`;}
function e(value:string):string{return value.replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!)}
